name: Java-Cmd

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: "Build and test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Create bin folder
      run: mkdir -p HelloTest/bin
    - name: Build classes
      run: javac -d HelloTest/bin -cp ./HelloTest/lib/junit/junit-4.13.2.jar:./HelloTest/lib/hamcrest/hamcrest-core-1.3.jar HelloTest/src/*.java
    - name: Run tests
      run: java -cp HelloTest/bin/:HelloTest/lib/junit/junit-4.13.2.jar:HelloTest/lib/hamcrest/hamcrest-core-1.3.jar org.junit.runner.JUnitCore CalculatorTest
